# Generated by Django 5.1.4 on 2026-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_emailverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="coins",
            field=models.IntegerField(default=0),
        ),
    ]
