# Generated by Django 5.1.4 on 2026-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_userprofile_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
